### ISSUE TITLE
Transcriber corner

### ISSUE THREAD

**Issue by EveSnyder** [historyforge/historyforge-old#180]
Hi Dave,
Once someone on Auburn HF goes to the transcribers corner they are redirected to the Ithaca HF when they try to get back to Auburn.  This happened to me once and I thought it was because I had an account on both but then it happened to two of the Auburn people as well.

**Comment by dfurber** [comment]
Well, yes, because that's what it does. I made the Ithaca one more general so as to be useful for Auburn too. Do you have City Directories and such for Auburn?

**Comment by EveSnyder** [comment]
I thought you wanted the transcribers corner to be generic for all the projects.  They are working on digitizing the 1910 city directory, it should be done by the new year.  They also have a list of street names, should I send those to you to put up once I have them?

**Comment by dfurber** [comment]
So I made a couple changes to help you make it happen.
1. The auburn page no longer points to ithaca.
2. A "document" can be a URL as well as an uploaded file, so that you can point to the manuals you are building on GitHub.
3. You may or may not have noticed the "Documents" and "Document Categories" items on the admin menu. This will help you organize them instead of that CMS editor which was not intended for this purpose.

Now there is no generic HF page. Instead, you should build the wiki to be the generic HF help guide, and upload docs specific to each HF instance to its Transcribers' Corner. And add links to the wiki to the transcribers pages.

**Comment by dfurber** [comment]
@EveSnyder please reply or close the issue if you are satisfied :)
